### ISSUE TITLE
but why ...

### ISSUE THREAD

**Issue by calvinmetcalf** [nolanlawson/rollup-plugin-inline-typeof#1]
I feel like I'm missing something, it seams like this is un-inlining code so that the code can be later inlined again, wouldn't that at best get you back to where you started ?

**Comment by calvinmetcalf** [comment]
ok looking at the interview it seems to be more about bundle size then performance,  I wonder if the reduction is bundle size holds up taking gzip into account

**Comment by nolanlawson** [comment]
yeah I was largely cargo-culting from the InfernoJS interview. When running actual perf tests it turned out to be a regression, at least in the case of PouchDB+in-memory+tempviews test: https://github.com/pouchdb/pouchdb/pull/6013#issuecomment-267114713

And yes, it did reduce the size for PouchDB both before and after gzip, but given the perf regression I would probably not recommend this module anymore. Hence why I added EXPERIMENTAL to the description.

**Comment by calvinmetcalf** [comment]
ok cool
